### ISSUE TITLE
Calling model.destroy() also destroys element containing collection if views are already wrapping in <li> tags

### ISSUE THREAD

**Issue by ewagstaff** [rotundasoftware/backbone.collectionView#70] opened 2016-01-05 18:32 UTC
The issue is due to this line: https://github.com/rotundasoftware/backbone.collectionView/blob/master/dist/backbone.collectionView.js#L467

Commenting out makes the method work as expected.

**Comment by dgbeck** [comment] 2016-01-07 23:43
Hi @ewagstaff ! Thanks very much for this bug report!

Can you be a little bit more explicit about what the problem is here? The DOM structure generally looks like this:

```
<ul>
   <li>
      <div></div>
   </li>
   ...
</ul>
```

where the `<div>` element is the modelView's `$el`. The intended behavior of the referenced line is to remove the `<li>` element that wraps the modelView div when a model view is removed from the collection. What behavior are you seeing instead?

Thank you!

**Comment by byronics** [comment] 2016-02-07 00:59
I'm experiencing the same issue.  My ModelView is an li, so it seems that in this case, the modelView.$el.parent().remove() on line 472 removes the ul containing the li.  If I change the ModelView to a div, the issue goes away.

**Comment by dgbeck** [comment] 2016-02-09 01:13
Gotcha, thanks for the clarification, @byronics !

I think this will now be fixed in v1.1.0, which was just published to npm

https://github.com/rotundasoftware/backbone.collectionView/blob/master/src/backbone.collectionView.js#L511

Can you give that a shot and let us know please?

Thanks!

**Comment by byronics** [comment] 2016-02-10 21:12
@dgbeck I just changed the `ModelView` to a `div`.  That seems like the best solution because it preserves the `data-model-cid`, `data-model-sortable` and other attributes that are added to the auto-generated `li` .  When my ModelView is itself an `li`, those attributes are not present.  I'm sure there are cases where that would cause problems.

**Comment by dgbeck** [comment] 2016-02-15 20:41
ah ok! FYI, as of v1.1.0, all the attributes / classes that are applied to the modelView element will also be applied to the `li` element, in the case that the modelView element *is* the `li`.

Closing. Thanks again to both of you for your help!

**Closed by dgbeck** 2016-02-15 20:41 UTC
